export const LEAGUES: { slug: string; name: string }[] = [
  { slug: "eng.1", name: "Premier League" },
  { slug: "eng.2", name: "Championship" },
  { slug: "eng.3", name: "League One" },
  { slug: "eng.4", name: "League Two" },
  { slug: "esp.1", name: "La Liga" },
  { slug: "esp.2", name: "La Liga 2" },
  { slug: "ita.1", name: "Serie A" },
  { slug: "ita.2", name: "Serie B" },
  { slug: "ger.1", name: "Bundesliga" },
  { slug: "ger.2", name: "2. Bundesliga" },
  { slug: "fra.1", name: "Ligue 1" },
  { slug: "fra.2", name: "Ligue 2" },
  { slug: "ned.1", name: "Eredivisie" },
  { slug: "ned.2", name: "Eerste Divisie" },
  { slug: "por.1", name: "Primeira Liga" },
  { slug: "bel.1", name: "Belgian Pro League" },
  { slug: "sco.1", name: "Scottish Premiership" },
  { slug: "tur.1", name: "Süper Lig" },
  { slug: "usa.1", name: "MLS" },
  { slug: "mex.1", name: "Liga MX" },
  { slug: "bra.1", name: "Brasileirão" },
  { slug: "bra.2", name: "Série B" },
  { slug: "arg.1", name: "Liga Profesional" },
  { slug: "arg.2", name: "Primera Nacional" },
  { slug: "swe.1", name: "Allsvenskan" },
  { slug: "den.1", name: "Superliga" },
  { slug: "col.1", name: "Liga BetPlay" },
  { slug: "chi.1", name: "Chilean Primera" },
  { slug: "ecu.1", name: "Liga Pro" },
  { slug: "club.friendly", name: "Club Friendly" },
  { slug: "uefa.champions", name: "Champions League" },
  { slug: "uefa.europa", name: "Europa League" },
];