import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{Bell,Brain,Check,ChevronRight,Clock,History,House,Plus,Search,ShieldBan,Star,TicketCheck,Trash2,X}from'lucide-react';import'./styles.css';

type Match={id:string;home:string;away:string;kickoff:string;league:string;homeLogo?:string;awayLogo?:string;markets:Record<string,number|null>};
type Pick={id:string;matchId:string;team:string;opponent:string;venue:'home'|'away';market:string;label:string;odds:number;kickoff:string;league:string;status:'pending'|'won'|'lost'|'void';createdAt:string};
type Ban={team:string;market?:string};
const MARKET_LABELS:Record<string,string>={homeWin:'Home win',draw:'Draw',awayWin:'Away win',over25:'Over 2.5',under25:'Under 2.5',bttsYes:'Both teams score',bttsNo:'Both teams not to score'};
const read=<T,>(k:string,d:T):T=>{try{return JSON.parse(localStorage.getItem(k)||'')??d}catch{return d}};
function App(){
 const[matches,setMatches]=useState<Match[]>([]),[picks,setPicks]=useState<Pick[]>(()=>read('ba:picks',[])),[bans,setBans]=useState<Ban[]>(()=>read('ba:bans',[])),[watch,setWatch]=useState<string[]>(()=>read('ba:watch',[])),[slip,setSlip]=useState<Pick[]>([]),[tab,setTab]=useState('home'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{fetch('/data/matches.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}).then(d=>{if(d.error)throw Error(d.error);setMatches(d.matches||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>localStorage.setItem('ba:picks',JSON.stringify(picks)),[picks]);useEffect(()=>localStorage.setItem('ba:bans',JSON.stringify(bans)),[bans]);useEffect(()=>localStorage.setItem('ba:watch',JSON.stringify(watch)),[watch]);
 const stats=useMemo(()=>{const settled=picks.filter(p=>p.status==='won'||p.status==='lost'),won=settled.filter(p=>p.status==='won');return{settled:settled.length,won:won.length,rate:settled.length?Math.round(won.length/settled.length*100):0}},[picks]);
 const memory=(team:string)=>{const a=picks.filter(p=>p.team===team&&p.status!=='pending'&&p.status!=='void');const by=new Map<string,{w:number,n:number}>();a.forEach(p=>{const x=by.get(p.label)||{w:0,n:0};x.n++;if(p.status==='won')x.w++;by.set(p.label,x)});return[...by].sort((a,b)=>b[1].w/b[1].n-a[1].w/a[1].n)[0]};
 const blocked=(team:string,market:string)=>bans.some(b=>b.team===team&&(!b.market||b.market===market));
 const add=(m:Match,market:string,odds:number)=>{const team=market==='awayWin'?m.away:m.home;if(blocked(team,market)){alert(`${team} ${MARKET_LABELS[market]} is on your blacklist.`);return}const p:Pick={id:`${m.id}:${market}`,matchId:m.id,team,opponent:team===m.home?m.away:m.home,venue:team===m.home?'home':'away',market,label:MARKET_LABELS[market],odds,kickoff:m.kickoff,league:m.league,status:'pending',createdAt:new Date().toISOString()};setSlip(s=>s.some(x=>x.id===p.id)?s.filter(x=>x.id!==p.id):[...s,p])};
 const saveSlip=()=>{setPicks(p=>[...slip,...p.filter(x=>!slip.some(s=>s.id===x.id))]);setSlip([]);setTab('history')};
 const visible=matches.filter(m=>(m.home+' '+m.away+' '+m.league).toLowerCase().includes(query.toLowerCase())).slice(0,80);
 const nav=[['home','Today',House],['history','My tips',History],['memory','Memory',Brain],['blacklist','Blacklist',ShieldBan]] as const;
 return <div className="app"><header><div className="brand"><span>B</span><div>BetAgree<small>Your betting memory</small></div></div><button className="icon"><Bell size={19}/>{watch.length>0&&<i/>}</button></header>
 <main>{tab==='home'&&<><section className="hero"><div><span className="eyebrow"><Brain size={13}/> PERSONAL MEMORY</span><h1>Your picks.<br/><em>Your patterns.</em></h1><p>Practice with virtual tips. BetAgree remembers what worked when the same team returns.</p></div><div className="score"><strong>{stats.rate}%</strong><span>personal hit rate</span><small>{stats.won} of {stats.settled} settled tips won</small></div></section><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search teams or leagues"/></div>{loading&&<div className="empty"><Clock/>Loading SportyBet matches…</div>}{error&&<div className="error">SportyBet feed: {error}</div>}<div className="section-title"><div><h2>Upcoming matches</h2><p>Live odds from SportyBet</p></div><span>{visible.length} games</span></div><div className="matches">{visible.map(m=><MatchCard key={m.id} m={m} memory={memory} watch={watch} setWatch={setWatch} slip={slip} add={add} blocked={blocked}/>)}</div></>}
 {tab==='history'&&<HistoryView picks={picks} setPicks={setPicks}/>} {tab==='memory'&&<MemoryView picks={picks}/>} {tab==='blacklist'&&<Blacklist bans={bans} setBans={setBans}/>}</main>
 {slip.length>0&&<div className="slip"><div><TicketCheck/><span><b>{slip.length} virtual tip{slip.length>1?'s':''}</b><small>Combined odds {slip.reduce((n,p)=>n*p.odds,1).toFixed(2)}</small></span></div><button onClick={saveSlip}>Save tips <ChevronRight size={18}/></button></div>}
 <nav>{nav.map(([id,label,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I/><span>{label}</span></button>)}</nav></div>
}
function MatchCard({m,memory,watch,setWatch,slip,add,blocked}:any){const mem=[memory(m.home),memory(m.away)].filter(Boolean)[0];const date=new Date(m.kickoff);const markets=Object.entries(m.markets).filter(([,v])=>typeof v==='number') as [string,number][];return <article className="match"><div className="match-top"><span>{m.league}</span><time>{date.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})} · {date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time><button onClick={()=>setWatch((w:string[])=>w.includes(m.home)?w.filter(x=>x!==m.home):[...w,m.home])}><Star size={17} fill={watch.includes(m.home)?'currentColor':'none'}/></button></div><div className="teams"><Team name={m.home} logo={m.homeLogo}/><b>VS</b><Team name={m.away} logo={m.awayLogo}/></div>{mem&&<div className="recall"><Brain size={16}/><div><b>Your memory: {mem[0]}</b><span>Landed {mem[1].w}/{mem[1].n} times with this team</span></div></div>}<div className="odds">{markets.slice(0,6).map(([k,v])=>{const team=k==='awayWin'?m.away:m.home;const on=slip.some((x:any)=>x.id===`${m.id}:${k}`),ban=blocked(team,k);return <button disabled={ban} className={on?'picked':''} onClick={()=>add(m,k,v)} key={k}><span>{MARKET_LABELS[k]||k}{ban&&' 🚫'}</span><b>{v.toFixed(2)}</b></button>})}</div></article>}
function Team({name,logo}:{name:string;logo?:string}){return <div className="team">{logo?<img src={logo}/>:<i>{name.slice(0,2).toUpperCase()}</i>}<strong>{name}</strong></div>}
function HistoryView({picks,setPicks}:any){const settle=(id:string,status:string)=>setPicks((ps:Pick[])=>ps.map(p=>p.id===id?{...p,status}:p));return <section><PageHead title="My virtual tips" sub="Settle your tips and BetAgree will learn from the result."/><div className="history">{!picks.length&&<Empty text="Your saved virtual tips will appear here."/>}{picks.map((p:Pick)=><article key={p.id}><div><small>{new Date(p.kickoff).toLocaleDateString()} · {p.league}</small><h3>{p.team} <span>vs {p.opponent}</span></h3><p>{p.label} <b>@ {p.odds.toFixed(2)}</b></p></div>{p.status==='pending'?<div className="settle"><button onClick={()=>settle(p.id,'won')}><Check/>Won</button><button onClick={()=>settle(p.id,'lost')}><X/>Lost</button></div>:<span className={'status '+p.status}>{p.status}</span>}</article>)}</div></section>}
function MemoryView({picks}:{picks:Pick[]}){const settled=picks.filter(p=>['won','lost'].includes(p.status));const groups=new Map<string,{w:number,n:number,market:string}>();settled.forEach(p=>{const k=p.team+'|'+p.label,x=groups.get(k)||{w:0,n:0,market:p.label};x.n++;if(p.status==='won')x.w++;groups.set(k,x)});const rows=[...groups].sort((a,b)=>b[1].w/b[1].n-a[1].w/a[1].n);return <section><PageHead title="Personal memory" sub="Patterns are based only on your own settled virtual tips."/><div className="memory-grid">{!rows.length&&<Empty text="Settle a few tips to begin building your personal memory."/>}{rows.map(([k,x])=><article key={k}><div className="memory-ring">{Math.round(x.w/x.n*100)}%</div><div><h3>{k.split('|')[0]}</h3><p>{x.market}</p><small>{x.w} wins from {x.n} selections</small></div></article>)}</div></section>}
function Blacklist({bans,setBans}:any){const[team,setTeam]=useState(''),[market,setMarket]=useState('');const add=()=>{if(team.trim()){setBans((b:Ban[])=>[...b,{team:team.trim(),market:market||undefined}]);setTeam('');setMarket('')}};return <section><PageHead title="Blacklist" sub="Block a whole team or only one market for that team."/><div className="ban-form"><input value={team} onChange={e=>setTeam(e.target.value)} placeholder="Team name"/><select value={market} onChange={e=>setMarket(e.target.value)}><option value="">All markets</option>{Object.entries(MARKET_LABELS).map(([k,v])=><option value={k}>{v}</option>)}</select><button onClick={add}><Plus/>Add</button></div><div className="ban-list">{bans.map((b:Ban,i:number)=><div><ShieldBan/><span><b>{b.team}</b><small>{b.market?MARKET_LABELS[b.market]:'Every market'}</small></span><button onClick={()=>setBans((x:Ban[])=>x.filter((_,j)=>j!==i))}><Trash2/></button></div>)}</div></section>}
function PageHead({title,sub}:{title:string;sub:string}){return <div className="page-head"><span className="eyebrow"><Brain size={13}/> BETAGREE</span><h1>{title}</h1><p>{sub}</p></div>}function Empty({text}:{text:string}){return <div className="empty"><Brain/>{text}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
