import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{Bell,Brain,Check,ChevronRight,Clock,History,House,Plus,Search,ShieldBan,Star,TicketCheck,Trash2,X}from'lucide-react';import'./styles.css';import'./suggestion.css';import'./tickets.css';

type Match={id:string;home:string;away:string;kickoff:string;league:string;homeLogo?:string;awayLogo?:string;markets:Record<string,number|null>};
type Pick={id:string;matchId:string;team:string;teams?:string[];opponent:string;venue:'home'|'away';market:string;label:string;odds:number;kickoff:string;league:string;status:'pending'|'won'|'lost'|'void';createdAt:string};
type Ticket={id:string;createdAt:string;stake:number;picks:Pick[]};
type Ban={team:string;market?:string};
const MARKET_LABELS:Record<string,string>={homeWin:'Home win',draw:'Draw',awayWin:'Away win',over25:'Over 2.5',under25:'Under 2.5',bttsYes:'Both teams score',bttsNo:'Both teams not to score'};
const memoryMarket=(p:Pick,team:string)=>{if((p.market==='homeWin'||p.market==='awayWin')&&p.team===team)return{key:'teamWin',label:'Team win'};if(['draw','over25','under25','bttsYes','bttsNo'].includes(p.market))return{key:p.market,label:p.label};return null};
const read=<T,>(k:string,d:T):T=>{try{return JSON.parse(localStorage.getItem(k)||'')??d}catch{return d}};
const loadTickets=()=>{const saved=read<Ticket[]>('ba:tickets',[]);if(saved.length)return saved;return read<Pick[]>('ba:picks',[]).map((p,i)=>({id:`LEGACY-${i+1}`,createdAt:p.createdAt,stake:10,picks:[p]}))};
const ticketState=(t:Ticket)=>t.picks.some(p=>p.status==='lost')?'lost':t.picks.some(p=>p.status==='pending')?'open':t.picks.every(p=>p.status==='void')?'void':'won';
const ticketOdds=(t:Ticket)=>t.picks.reduce((n,p)=>n*(p.status==='void'?1:p.odds),1);
function App(){
 const[matches,setMatches]=useState<Match[]>([]),[tickets,setTickets]=useState<Ticket[]>(loadTickets),[bans,setBans]=useState<Ban[]>(()=>read('ba:bans',[])),[watch,setWatch]=useState<string[]>(()=>read('ba:watch',[])),[slip,setSlip]=useState<Pick[]>([]),[stake,setStake]=useState(10),[tab,setTab]=useState('home'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const picks=useMemo(()=>tickets.flatMap(t=>t.picks),[tickets]);
 useEffect(()=>{fetch('/data/matches.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}).then(d=>{if(d.error)throw Error(d.error);setMatches(d.matches||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>localStorage.setItem('ba:tickets',JSON.stringify(tickets)),[tickets]);useEffect(()=>localStorage.setItem('ba:bans',JSON.stringify(bans)),[bans]);useEffect(()=>localStorage.setItem('ba:watch',JSON.stringify(watch)),[watch]);
 const stats=useMemo(()=>{const settled=picks.filter(p=>p.status==='won'||p.status==='lost'),won=settled.filter(p=>p.status==='won');return{settled:settled.length,won:won.length,rate:settled.length?Math.round(won.length/settled.length*100):0}},[picks]);
 const memory=(team:string)=>{const by=new Map<string,{team:string;key:string;label:string;w:number;n:number;score:number}>();picks.filter(p=>['won','lost'].includes(p.status)&&(p.teams?.includes(team)||(!p.teams&&p.team===team))).forEach(p=>{const mm=memoryMarket(p,team);if(!mm)return;const x=by.get(mm.key)||{team,key:mm.key,label:mm.label,w:0,n:0,score:0};x.n++;if(p.status==='won')x.w++;x.score=(x.w+1)/(x.n+2)+Math.min(x.n,8)*.01;by.set(mm.key,x)});return[...by.values()].sort((a,b)=>b.score-a.score||b.n-a.n)[0]};
 const blocked=(team:string,market:string)=>bans.some(b=>b.team===team&&(!b.market||b.market===market));
 const add=(m:Match,market:string,odds:number)=>{const team=market==='awayWin'?m.away:m.home;if(blocked(team,market)){alert(`${team} ${MARKET_LABELS[market]} is on your blacklist.`);return}const teams=['draw','over25','under25','bttsYes','bttsNo'].includes(market)?[m.home,m.away]:[team];const p:Pick={id:`${m.id}:${market}`,matchId:m.id,team,teams,opponent:team===m.home?m.away:m.home,venue:team===m.home?'home':'away',market,label:MARKET_LABELS[market],odds,kickoff:m.kickoff,league:m.league,status:'pending',createdAt:new Date().toISOString()};setSlip(s=>s.some(x=>x.id===p.id)?s.filter(x=>x.id!==p.id):[...s,p])};
 const saveSlip=()=>{if(!slip.length)return;const ticket:Ticket={id:`BA-${Date.now().toString().slice(-8)}`,createdAt:new Date().toISOString(),stake:Math.max(1,Number(stake)||1),picks:slip};setTickets(t=>[ticket,...t]);setSlip([]);setStake(10);setTab('history')};
 const visible=matches.filter(m=>(m.home+' '+m.away+' '+m.league).toLowerCase().includes(query.toLowerCase())).slice(0,80);
 const nav=[['home','Today',House],['history','My tips',History],['memory','Memory',Brain],['blacklist','Blacklist',ShieldBan]] as const;
 return <div className="app"><header><div className="brand"><span>B</span><div>BetAgree<small>Your betting memory</small></div></div><button className="icon"><Bell size={19}/>{watch.length>0&&<i/>}</button></header>
 <main>{tab==='home'&&<><section className="hero"><div><span className="eyebrow"><Brain size={13}/> PERSONAL MEMORY</span><h1>Your picks.<br/><em>Your patterns.</em></h1><p>Practice with virtual tips. BetAgree remembers what worked when the same team returns.</p></div><div className="score"><strong>{stats.rate}%</strong><span>personal hit rate</span><small>{stats.won} of {stats.settled} settled tips won</small></div></section><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search teams or leagues"/></div>{loading&&<div className="empty"><Clock/>Loading SportyBet matches…</div>}{error&&<div className="error">SportyBet feed: {error}</div>}<div className="section-title"><div><h2>Upcoming matches</h2><p>Live odds from SportyBet</p></div><span>{visible.length} games</span></div><div className="matches">{visible.map(m=><MatchCard key={m.id} m={m} memory={memory} watch={watch} setWatch={setWatch} slip={slip} add={add} blocked={blocked}/>)}</div></>}
 {tab==='history'&&<HistoryView tickets={tickets} setTickets={setTickets}/>} {tab==='memory'&&<MemoryView picks={picks}/>} {tab==='blacklist'&&<Blacklist bans={bans} setBans={setBans}/>}</main>
 {slip.length>0&&<div className="slip"><div className="slip-title"><TicketCheck/><span><b>{slip.length}-leg virtual slip</b><small>Total odds {slip.reduce((n,p)=>n*p.odds,1).toFixed(2)}</small></span></div><label>Stake (VC)<input type="number" min="1" step="1" value={stake} onChange={e=>setStake(Number(e.target.value))}/></label><div className="slip-return"><small>Potential return</small><b>{(Math.max(1,stake||1)*slip.reduce((n,p)=>n*p.odds,1)).toFixed(2)} VC</b></div><button onClick={saveSlip}>Place virtual slip <ChevronRight size={18}/></button></div>}
 <nav>{nav.map(([id,label,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I/><span>{label}</span></button>)}</nav></div>
}
function MatchCard({m,memory,watch,setWatch,slip,add,blocked}:any){const histories=[memory(m.home),memory(m.away)].filter(Boolean).map((x:any)=>{const market=x.key==='teamWin'?(x.team===m.home?'homeWin':'awayWin'):x.key;return{...x,market,odds:m.markets[market]}}).filter((x:any)=>typeof x.odds==='number').sort((a:any,b:any)=>b.score-a.score||b.n-a.n);const suggestion=histories[0];const date=new Date(m.kickoff);const markets=Object.entries(m.markets).filter(([,v])=>typeof v==='number') as [string,number][];return <article className="match"><div className="match-top"><span>{m.league}</span><time>{date.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})} · {date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time><button onClick={()=>setWatch((w:string[])=>w.includes(m.home)?w.filter(x=>x!==m.home):[...w,m.home])}><Star size={17} fill={watch.includes(m.home)?'currentColor':'none'}/></button></div><div className="teams"><Team name={m.home} logo={m.homeLogo}/><b>VS</b><Team name={m.away} logo={m.awayLogo}/></div>{suggestion&&<div className="recall suggestion"><Brain size={17}/><div><small>Suggested from your history</small><b>{suggestion.team}: {suggestion.label}</b><span>Worked {suggestion.w}/{suggestion.n} times across your settled tips</span></div><button disabled={blocked(suggestion.team,suggestion.market)} onClick={()=>add(m,suggestion.market,suggestion.odds)}>Add @ {suggestion.odds.toFixed(2)}</button></div>}<div className="odds">{markets.slice(0,6).map(([k,v])=>{const team=k==='awayWin'?m.away:m.home;const on=slip.some((x:any)=>x.id===`${m.id}:${k}`),ban=blocked(team,k);return <button disabled={ban} className={on?'picked':''} onClick={()=>add(m,k,v)} key={k}><span>{MARKET_LABELS[k]||k}{ban&&' 🚫'}</span><b>{v.toFixed(2)}</b></button>})}</div></article>}
function Team({name,logo}:{name:string;logo?:string}){return <div className="team">{logo?<img src={logo}/>:<i>{name.slice(0,2).toUpperCase()}</i>}<strong>{name}</strong></div>}
function HistoryView({tickets,setTickets}:{tickets:Ticket[];setTickets:React.Dispatch<React.SetStateAction<Ticket[]>>}){const settle=(ticketId:string,pickId:string,status:Pick['status'])=>setTickets(ts=>ts.map(t=>t.id===ticketId?{...t,picks:t.picks.map(p=>p.id===pickId?{...p,status}:p)}:t));return <section><PageHead title="My virtual slips" sub="Each ticket settles like a real accumulator: one losing leg loses the slip; every active leg must win."/><div className="tickets">{!tickets.length&&<Empty text="Your saved virtual slips will appear here."/>}{tickets.map(t=>{const state=ticketState(t),odds=ticketOdds(t),amount=state==='lost'?0:state==='void'?t.stake:t.stake*odds;return <article className={`ticket ticket-${state}`} key={t.id}><header className="ticket-head"><div><small>Virtual ticket</small><b>#{t.id}</b><span>{new Date(t.createdAt).toLocaleString()}</span></div><strong className={`ticket-state ${state}`}>{state}</strong></header><div className="ticket-legs">{t.picks.map((p,i)=><div className={`ticket-leg leg-${p.status}`} key={p.id}><div className="leg-number">{i+1}</div><div className="leg-copy"><small>{p.league} · {new Date(p.kickoff).toLocaleDateString()}</small><h3>{p.team} <span>vs {p.opponent}</span></h3><p>{p.label} <b>@ {p.odds.toFixed(2)}</b></p></div>{p.status==='pending'?<div className="settle"><button onClick={()=>settle(t.id,p.id,'won')}><Check/>Won</button><button onClick={()=>settle(t.id,p.id,'lost')}><X/>Lost</button><button onClick={()=>settle(t.id,p.id,'void')}><Clock/>Void</button></div>:<span className={`status ${p.status}`}>{p.status}</span>}</div>)}</div><footer className="ticket-foot"><div><small>Virtual stake</small><b>{t.stake.toFixed(2)} VC</b></div><div><small>Adjusted odds</small><b>{odds.toFixed(2)}</b></div><div><small>{state==='won'?'Return':state==='lost'?'Return':state==='void'?'Refund':'Potential return'}</small><b>{amount.toFixed(2)} VC</b></div></footer></article>})}</div></section>}
function MemoryView({picks}:{picks:Pick[]}){const groups=new Map<string,{w:number,n:number;market:string}>();picks.filter(p=>['won','lost'].includes(p.status)).forEach(p=>(p.teams||[p.team]).forEach(team=>{const mm=memoryMarket(p,team);if(!mm)return;const k=team+'|'+mm.key,x=groups.get(k)||{w:0,n:0,market:mm.label};x.n++;if(p.status==='won')x.w++;groups.set(k,x)}));const rows=[...groups].sort((a,b)=>b[1].w/b[1].n-a[1].w/a[1].n||b[1].n-a[1].n);return <section><PageHead title="Personal memory" sub="Patterns are based on all your settled virtual tips for each team."/><div className="memory-grid">{!rows.length&&<Empty text="Settle a few tips to begin building your personal memory."/>}{rows.map(([k,x])=><article key={k}><div className="memory-ring">{Math.round(x.w/x.n*100)}%</div><div><h3>{k.split('|')[0]}</h3><p>{x.market}</p><small>{x.w} wins from {x.n} selections</small></div></article>)}</div></section>}
function Blacklist({bans,setBans}:any){const[team,setTeam]=useState(''),[market,setMarket]=useState('');const add=()=>{if(team.trim()){setBans((b:Ban[])=>[...b,{team:team.trim(),market:market||undefined}]);setTeam('');setMarket('')}};return <section><PageHead title="Blacklist" sub="Block a whole team or only one market for that team."/><div className="ban-form"><input value={team} onChange={e=>setTeam(e.target.value)} placeholder="Team name"/><select value={market} onChange={e=>setMarket(e.target.value)}><option value="">All markets</option>{Object.entries(MARKET_LABELS).map(([k,v])=><option value={k}>{v}</option>)}</select><button onClick={add}><Plus/>Add</button></div><div className="ban-list">{bans.map((b:Ban,i:number)=><div><ShieldBan/><span><b>{b.team}</b><small>{b.market?MARKET_LABELS[b.market]:'Every market'}</small></span><button onClick={()=>setBans((x:Ban[])=>x.filter((_,j)=>j!==i))}><Trash2/></button></div>)}</div></section>}
function PageHead({title,sub}:{title:string;sub:string}){return <div className="page-head"><span className="eyebrow"><Brain size={13}/> BETAGREE</span><h1>{title}</h1><p>{sub}</p></div>}function Empty({text}:{text:string}){return <div className="empty"><Brain/>{text}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
