/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccuracyRouteImport } from './routes/accuracy'
import { Route as BoardRouteImport } from './routes/board'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as TipstersRouteImport } from './routes/tipsters'
import { Route as ApiLedgerRouteImport } from './routes/api/ledger'
import { Route as ApiSlateRouteImport } from './routes/api/slate'
import { Route as FixturesIndexRouteImport } from './routes/fixtures.index'
import { Route as FixturesIdRouteImport } from './routes/fixtures.$id'
import { Route as TipstersIndexRouteImport } from './routes/tipsters.index'
import { Route as TipstersIdRouteImport } from './routes/tipsters.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccuracyRoute = AccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const TipstersRoute = TipstersRouteImport.update({
  id: '/tipsters',
  path: '/tipsters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerRoute = ApiLedgerRouteImport.update({
  id: '/api/ledger',
  path: '/api/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlateRoute = ApiSlateRouteImport.update({
  id: '/api/slate',
  path: '/api/slate',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesIndexRoute = FixturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FixturesRoute,
} as any)
const FixturesIdRoute = FixturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FixturesRoute,
} as any)
const TipstersIndexRoute = TipstersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TipstersRoute,
} as any)
const TipstersIdRoute = TipstersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TipstersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/board': typeof BoardRoute
  '/fixtures': typeof FixturesRouteWithChildren
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRoute
  '/tipsters': typeof TipstersRouteWithChildren
  '/api/ledger': typeof ApiLedgerRoute
  '/api/slate': typeof ApiSlateRoute
  '/fixtures/$id': typeof FixturesIdRoute
  '/tipsters/$id': typeof TipstersIdRoute
  '/fixtures/': typeof FixturesIndexRoute
  '/tipsters/': typeof TipstersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/board': typeof BoardRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/slate': typeof ApiSlateRoute
  '/fixtures/$id': typeof FixturesIdRoute
  '/tipsters/$id': typeof TipstersIdRoute
  '/fixtures': typeof FixturesIndexRoute
  '/tipsters': typeof TipstersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/board': typeof BoardRoute
  '/fixtures': typeof FixturesRouteWithChildren
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRoute
  '/tipsters': typeof TipstersRouteWithChildren
  '/api/ledger': typeof ApiLedgerRoute
  '/api/slate': typeof ApiSlateRoute
  '/fixtures/$id': typeof FixturesIdRoute
  '/tipsters/$id': typeof TipstersIdRoute
  '/fixtures/': typeof FixturesIndexRoute
  '/tipsters/': typeof TipstersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accuracy'
    | '/board'
    | '/fixtures'
    | '/login'
    | '/playbook'
    | '/tipsters'
    | '/api/ledger'
    | '/api/slate'
    | '/fixtures/$id'
    | '/tipsters/$id'
    | '/fixtures/'
    | '/tipsters/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accuracy'
    | '/board'
    | '/login'
    | '/playbook'
    | '/api/ledger'
    | '/api/slate'
    | '/fixtures/$id'
    | '/tipsters/$id'
    | '/fixtures'
    | '/tipsters'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/accuracy'
    | '/board'
    | '/fixtures'
    | '/login'
    | '/playbook'
    | '/tipsters'
    | '/api/ledger'
    | '/api/slate'
    | '/fixtures/$id'
    | '/tipsters/$id'
    | '/fixtures/'
    | '/tipsters/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccuracyRoute: typeof AccuracyRoute
  BoardRoute: typeof BoardRoute
  FixturesRoute: typeof FixturesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlaybookRoute: typeof PlaybookRoute
  TipstersRoute: typeof TipstersRouteWithChildren
  ApiLedgerRoute: typeof ApiLedgerRoute
  ApiSlateRoute: typeof ApiSlateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accuracy': {
      id: '/accuracy'
      path: '/accuracy'
      fullPath: '/accuracy'
      preLoaderRoute: typeof AccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipsters': {
      id: '/tipsters'
      path: '/tipsters'
      fullPath: '/tipsters'
      preLoaderRoute: typeof TipstersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger': {
      id: '/api/ledger'
      path: '/api/ledger'
      fullPath: '/api/ledger'
      preLoaderRoute: typeof ApiLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slate': {
      id: '/api/slate'
      path: '/api/slate'
      fullPath: '/api/slate'
      preLoaderRoute: typeof ApiSlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/': {
      id: '/fixtures/'
      path: '/'
      fullPath: '/fixtures/'
      preLoaderRoute: typeof FixturesIndexRouteImport
      parentRoute: typeof FixturesRoute
    }
    '/fixtures/$id': {
      id: '/fixtures/$id'
      path: '/$id'
      fullPath: '/fixtures/$id'
      preLoaderRoute: typeof FixturesIdRouteImport
      parentRoute: typeof FixturesRoute
    }
    '/tipsters/': {
      id: '/tipsters/'
      path: '/'
      fullPath: '/tipsters/'
      preLoaderRoute: typeof TipstersIndexRouteImport
      parentRoute: typeof TipstersRoute
    }
    '/tipsters/$id': {
      id: '/tipsters/$id'
      path: '/$id'
      fullPath: '/tipsters/$id'
      preLoaderRoute: typeof TipstersIdRouteImport
      parentRoute: typeof TipstersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FixturesRouteChildren {
  FixturesIdRoute: typeof FixturesIdRoute
  FixturesIndexRoute: typeof FixturesIndexRoute
}

const FixturesRouteChildren: FixturesRouteChildren = {
  FixturesIdRoute: FixturesIdRoute,
  FixturesIndexRoute: FixturesIndexRoute,
}

const FixturesRouteWithChildren = FixturesRoute._addFileChildren(
  FixturesRouteChildren,
)

interface TipstersRouteChildren {
  TipstersIdRoute: typeof TipstersIdRoute
  TipstersIndexRoute: typeof TipstersIndexRoute
}

const TipstersRouteChildren: TipstersRouteChildren = {
  TipstersIdRoute: TipstersIdRoute,
  TipstersIndexRoute: TipstersIndexRoute,
}

const TipstersRouteWithChildren = TipstersRoute._addFileChildren(
  TipstersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccuracyRoute: AccuracyRoute,
  BoardRoute: BoardRoute,
  FixturesRoute: FixturesRouteWithChildren,
  LoginRoute: LoginRoute,
  PlaybookRoute: PlaybookRoute,
  TipstersRoute: TipstersRouteWithChildren,
  ApiLedgerRoute: ApiLedgerRoute,
  ApiSlateRoute: ApiSlateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
