/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccuracyRouteImport } from './routes/accuracy'
import { Route as BankerRouteImport } from './routes/banker'
import { Route as BoardRouteImport } from './routes/board'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as FormRouteImport } from './routes/form'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OddsRouteImport } from './routes/odds'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as StreaksRouteImport } from './routes/streaks'
import { Route as TipstersRouteImport } from './routes/tipsters'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as ApiCrestRouteImport } from './routes/api/crest'
import { Route as ApiFormRouteImport } from './routes/api/form'
import { Route as ApiLedgerRouteImport } from './routes/api/ledger'
import { Route as ApiOddsRouteImport } from './routes/api/odds'
import { Route as ApiScoresRouteImport } from './routes/api/scores'
import { Route as ApiSlateRouteImport } from './routes/api/slate'
import { Route as ApiStreaksRouteImport } from './routes/api/streaks'
import { Route as ApiTrendsRouteImport } from './routes/api/trends'
import { Route as FixturesIndexRouteImport } from './routes/fixtures.index'
import { Route as FixturesIdRouteImport } from './routes/fixtures.$id'
import { Route as TipstersIndexRouteImport } from './routes/tipsters.index'
import { Route as TipstersIdRouteImport } from './routes/tipsters.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccuracyRoute = AccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const BankerRoute = BankerRouteImport.update({
  id: '/banker',
  path: '/banker',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OddsRoute = OddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const StreaksRoute = StreaksRouteImport.update({
  id: '/streaks',
  path: '/streaks',
  getParentRoute: () => rootRouteImport,
} as any)
const TipstersRoute = TipstersRouteImport.update({
  id: '/tipsters',
  path: '/tipsters',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrestRoute = ApiCrestRouteImport.update({
  id: '/api/crest',
  path: '/api/crest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormRoute = ApiFormRouteImport.update({
  id: '/api/form',
  path: '/api/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerRoute = ApiLedgerRouteImport.update({
  id: '/api/ledger',
  path: '/api/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOddsRoute = ApiOddsRouteImport.update({
  id: '/api/odds',
  path: '/api/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoresRoute = ApiScoresRouteImport.update({
  id: '/api/scores',
  path: '/api/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlateRoute = ApiSlateRouteImport.update({
  id: '/api/slate',
  path: '/api/slate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreaksRoute = ApiStreaksRouteImport.update({
  id: '/api/streaks',
  path: '/api/streaks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendsRoute = ApiTrendsRouteImport.update({
  id: '/api/trends',
  path: '/api/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesIndexRoute = FixturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FixturesRoute,
} as any)
const FixturesIdRoute = FixturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FixturesRoute,
} as any)
const TipstersIndexRoute = TipstersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TipstersRoute,
} as any)
const TipstersIdRoute = TipstersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TipstersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/banker': typeof BankerRoute
  '/board': typeof BoardRoute
  '/fixtures': typeof FixturesRouteWithChildren
  '/form': typeof FormRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/odds': typeof OddsRoute
  '/playbook': typeof PlaybookRoute
  '/streaks': typeof StreaksRoute
  '/tipsters': typeof TipstersRouteWithChildren
  '/trends': typeof TrendsRoute
  '/api/crest': typeof ApiCrestRoute
  '/api/form': typeof ApiFormRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/odds': typeof ApiOddsRoute
  '/api/scores': typeof ApiScoresRoute
  '/api/slate': typeof ApiSlateRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/trends': typeof ApiTrendsRoute
  '/fixtures/$id': typeof FixturesIdRoute
  '/tipsters/$id': typeof TipstersIdRoute
  '/fixtures/': typeof FixturesIndexRoute
  '/tipsters/': typeof TipstersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/banker': typeof BankerRoute
  '/board': typeof BoardRoute
  '/form': typeof FormRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/odds': typeof OddsRoute
  '/playbook': typeof PlaybookRoute
  '/streaks': typeof StreaksRoute
  '/trends': typeof TrendsRoute
  '/api/crest': typeof ApiCrestRoute
  '/api/form': typeof ApiFormRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/odds': typeof ApiOddsRoute
  '/api/scores': typeof ApiScoresRoute
  '/api/slate': typeof ApiSlateRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/trends': typeof ApiTrendsRoute
  '/fixtures/$id': typeof FixturesIdRoute
  '/tipsters/$id': typeof TipstersIdRoute
  '/fixtures': typeof FixturesIndexRoute
  '/tipsters': typeof TipstersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/banker': typeof BankerRoute
  '/board': typeof BoardRoute
  '/fixtures': typeof FixturesRouteWithChildren
  '/form': typeof FormRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/odds': typeof OddsRoute
  '/playbook': typeof PlaybookRoute
  '/streaks': typeof StreaksRoute
  '/tipsters': typeof TipstersRouteWithChildren
  '/trends': typeof TrendsRoute
  '/api/crest': typeof ApiCrestRoute
  '/api/form': typeof ApiFormRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/odds': typeof ApiOddsRoute
  '/api/scores': typeof ApiScoresRoute
  '/api/slate': typeof ApiSlateRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/trends': typeof ApiTrendsRoute
  '/fixtures/$id': typeof FixturesIdRoute
  '/tipsters/$id': typeof TipstersIdRoute
  '/fixtures/': typeof FixturesIndexRoute
  '/tipsters/': typeof TipstersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accuracy'
    | '/banker'
    | '/board'
    | '/fixtures'
    | '/form'
    | '/live'
    | '/login'
    | '/odds'
    | '/playbook'
    | '/streaks'
    | '/tipsters'
    | '/trends'
    | '/api/crest'
    | '/api/form'
    | '/api/ledger'
    | '/api/odds'
    | '/api/scores'
    | '/api/slate'
    | '/api/streaks'
    | '/api/trends'
    | '/fixtures/$id'
    | '/tipsters/$id'
    | '/fixtures/'
    | '/tipsters/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accuracy'
    | '/banker'
    | '/board'
    | '/form'
    | '/live'
    | '/login'
    | '/odds'
    | '/playbook'
    | '/streaks'
    | '/trends'
    | '/api/crest'
    | '/api/form'
    | '/api/ledger'
    | '/api/odds'
    | '/api/scores'
    | '/api/slate'
    | '/api/streaks'
    | '/api/trends'
    | '/fixtures/$id'
    | '/tipsters/$id'
    | '/fixtures'
    | '/tipsters'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/accuracy'
    | '/banker'
    | '/board'
    | '/fixtures'
    | '/form'
    | '/live'
    | '/login'
    | '/odds'
    | '/playbook'
    | '/streaks'
    | '/tipsters'
    | '/trends'
    | '/api/crest'
    | '/api/form'
    | '/api/ledger'
    | '/api/odds'
    | '/api/scores'
    | '/api/slate'
    | '/api/streaks'
    | '/api/trends'
    | '/fixtures/$id'
    | '/tipsters/$id'
    | '/fixtures/'
    | '/tipsters/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccuracyRoute: typeof AccuracyRoute
  BankerRoute: typeof BankerRoute
  BoardRoute: typeof BoardRoute
  FixturesRoute: typeof FixturesRouteWithChildren
  FormRoute: typeof FormRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  OddsRoute: typeof OddsRoute
  PlaybookRoute: typeof PlaybookRoute
  StreaksRoute: typeof StreaksRoute
  TipstersRoute: typeof TipstersRouteWithChildren
  TrendsRoute: typeof TrendsRoute
  ApiCrestRoute: typeof ApiCrestRoute
  ApiFormRoute: typeof ApiFormRoute
  ApiLedgerRoute: typeof ApiLedgerRoute
  ApiOddsRoute: typeof ApiOddsRoute
  ApiScoresRoute: typeof ApiScoresRoute
  ApiSlateRoute: typeof ApiSlateRoute
  ApiStreaksRoute: typeof ApiStreaksRoute
  ApiTrendsRoute: typeof ApiTrendsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accuracy': {
      id: '/accuracy'
      path: '/accuracy'
      fullPath: '/accuracy'
      preLoaderRoute: typeof AccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banker': {
      id: '/banker'
      path: '/banker'
      fullPath: '/banker'
      preLoaderRoute: typeof BankerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odds': {
      id: '/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof OddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaks': {
      id: '/streaks'
      path: '/streaks'
      fullPath: '/streaks'
      preLoaderRoute: typeof StreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipsters': {
      id: '/tipsters'
      path: '/tipsters'
      fullPath: '/tipsters'
      preLoaderRoute: typeof TipstersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crest': {
      id: '/api/crest'
      path: '/api/crest'
      fullPath: '/api/crest'
      preLoaderRoute: typeof ApiCrestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form': {
      id: '/api/form'
      path: '/api/form'
      fullPath: '/api/form'
      preLoaderRoute: typeof ApiFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger': {
      id: '/api/ledger'
      path: '/api/ledger'
      fullPath: '/api/ledger'
      preLoaderRoute: typeof ApiLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/odds': {
      id: '/api/odds'
      path: '/api/odds'
      fullPath: '/api/odds'
      preLoaderRoute: typeof ApiOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scores': {
      id: '/api/scores'
      path: '/api/scores'
      fullPath: '/api/scores'
      preLoaderRoute: typeof ApiScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slate': {
      id: '/api/slate'
      path: '/api/slate'
      fullPath: '/api/slate'
      preLoaderRoute: typeof ApiSlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streaks': {
      id: '/api/streaks'
      path: '/api/streaks'
      fullPath: '/api/streaks'
      preLoaderRoute: typeof ApiStreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trends': {
      id: '/api/trends'
      path: '/api/trends'
      fullPath: '/api/trends'
      preLoaderRoute: typeof ApiTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/': {
      id: '/fixtures/'
      path: '/'
      fullPath: '/fixtures/'
      preLoaderRoute: typeof FixturesIndexRouteImport
      parentRoute: typeof FixturesRoute
    }
    '/fixtures/$id': {
      id: '/fixtures/$id'
      path: '/$id'
      fullPath: '/fixtures/$id'
      preLoaderRoute: typeof FixturesIdRouteImport
      parentRoute: typeof FixturesRoute
    }
    '/tipsters/': {
      id: '/tipsters/'
      path: '/'
      fullPath: '/tipsters/'
      preLoaderRoute: typeof TipstersIndexRouteImport
      parentRoute: typeof TipstersRoute
    }
    '/tipsters/$id': {
      id: '/tipsters/$id'
      path: '/$id'
      fullPath: '/tipsters/$id'
      preLoaderRoute: typeof TipstersIdRouteImport
      parentRoute: typeof TipstersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FixturesRouteChildren {
  FixturesIdRoute: typeof FixturesIdRoute
  FixturesIndexRoute: typeof FixturesIndexRoute
}

const FixturesRouteChildren: FixturesRouteChildren = {
  FixturesIdRoute: FixturesIdRoute,
  FixturesIndexRoute: FixturesIndexRoute,
}

const FixturesRouteWithChildren = FixturesRoute._addFileChildren(
  FixturesRouteChildren,
)

interface TipstersRouteChildren {
  TipstersIdRoute: typeof TipstersIdRoute
  TipstersIndexRoute: typeof TipstersIndexRoute
}

const TipstersRouteChildren: TipstersRouteChildren = {
  TipstersIdRoute: TipstersIdRoute,
  TipstersIndexRoute: TipstersIndexRoute,
}

const TipstersRouteWithChildren = TipstersRoute._addFileChildren(
  TipstersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccuracyRoute: AccuracyRoute,
  BankerRoute: BankerRoute,
  BoardRoute: BoardRoute,
  FixturesRoute: FixturesRouteWithChildren,
  FormRoute: FormRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  OddsRoute: OddsRoute,
  PlaybookRoute: PlaybookRoute,
  StreaksRoute: StreaksRoute,
  TipstersRoute: TipstersRouteWithChildren,
  TrendsRoute: TrendsRoute,
  ApiCrestRoute: ApiCrestRoute,
  ApiFormRoute: ApiFormRoute,
  ApiLedgerRoute: ApiLedgerRoute,
  ApiOddsRoute: ApiOddsRoute,
  ApiScoresRoute: ApiScoresRoute,
  ApiSlateRoute: ApiSlateRoute,
  ApiStreaksRoute: ApiStreaksRoute,
  ApiTrendsRoute: ApiTrendsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
